name: Build ESP32 Plane Radar

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"

      - name: Install PlatformIO
        run: pip install --upgrade platformio

      - name: Build firmware
        run: pio run

      - name: Upload firmware
        uses: actions/upload-artifact@v7
        with:
          name: ESP32-Plane-Radar-v1.1.3-weather-clock
          path: |
            .pio/build/**/firmware.bin
            .pio/build/**/firmware.elf
          if-no-files-found: error
